language: node_js
node_js:
  - lts/*

cache:
  directories:
    - node_modules

branches:
  only:
    - master

before_script:
  - yarn global add firebase-tools
  - yarn

script:
  - yarn test
  - yarn build

after_success:
  - firebase deploy --project pysakkiopas --token $FIREBASE_TOKEN --non-interactive
