language: node_js
node_js:
  - 4
  - 6
cache:
  directories:
    - node_modules
script:
  - npm test
  - npm run build

deploy:
  provider: firebase
  token:
    secure: "spPyqp/yV8xTqMDvItueX/2YNceUl9/B1LbH5SwcQn7OkoJCBTGCrfGvMiHovc/GJIbTyxQGFVJBrSzUbnZqbYCOnfKs9hbcsxtHRbsPv0xAw11zl87mwfX6/UNejyJuVZV+1uA54YJh5r6b5fEt1FmvKlArDD/E1wC8kmibvzYn2RYb1XyKWQPplNJ4SpbwC/hFkIu8R+jgPbrn8AT5nbryBNaorKQQMmwn7SwfuFYad/qPgGTpye9BGY2o0MxKmi+YO4UcHmC7SrHhtY5bEYJfPbrNLUVVXqFC7nwj9vxOkLpJfDvyUIUQI/uiWKObec4Jq1PpkYP9WNvxsrqWvK8ehNCFUCP5OysWCxJYhuM3vP0/kp7ORMJFDgnewVmu3ftnKFaQfKlpjqjQFiI1D5/p6sao3HUW+mn5X6/wbR+EGpumVbnVmuiI/66eKOjdaDKSfHzA3RfYI9oFZmoPxj/TZpcYFVUHTMIciQ1cRogh/AUlzFNlGrGi8QrkSP1mU4xHhcw3FseNdhqvQ6GWpyOB8b6EryGj6Bluo0leW1P+/ae62U/2g65rUqX/C/myqgM549/I1sq+9cVxr3CFTLOfEiGaD6MS+DlmOXzrP1ZXiCk3zi2TafDmhbFDH6v+wG/sDal8b6/c3j/aUjM7SB5HAGgX4zCMIKtiaBbo++4="
  project: "react-ohjelmointiprojekti"
