language: node_js
node_js:
  - 4
  - 6
cache:
  directories:
    - node_modules
script:
  - npm test
  - npm run build

deploy:
  provider: firebase
  token:
    secure: "ZHOwN6TYaBAVA8cSwn30PfSNs/UachFI3fZelC7DMbjBX68qvav7HDzgR2k+s18dPJi3Rq/XUQAxgvGR2n8/79NobInYlg/QNmMZ03FRhBh0BQ/WxtSOTVzDn2EBWe9syeLGYwuAnEPDfqIo8m3KhCIz1gfbbdt6hcb/bI2ADHdSnKJjBsVmCKkho/zh4gUNYfcfPCbxM7/wT0qSr+wTxkTDa20m97L212vn4YQ0cguWrDt4qX13EkySjQYwXH4p35tTMmgamHvPm9jbMl2IYJcmJ1Ej2I3eF/7mgGRr1v1W0m1egP8NTv76iR02lDTcacZhmZFU99OgxnHVlcn0kogN2fjoIYNzF5w8oH/QSV6/6C+2+uIqRQaCYnCJ3n6RToPdmvytJrybVls6TFR3+KEVXcU92roU3T06IaTEYwySHGOKfvgcdxc+pLQs+R4nZjilY6nhQ7mO4EZbck8SLLtnev18YaRLyw+pgZ+HBVjWK69LymEVmupDSDY8d8uJzi6J7UHcxyT95eHX+WKpHY/3g/t+KcT6CWa3wxVCf2fH0xF6QWgERzvB55pJbMLm4HeqlxCFio0/g9ITUCHnvLujdr5S8Z7U0MOpfKh9Ibn5rrQjVpKYVExXGVVauU/yQoDTXJIVlDatwJ0foLk+xm6ATSEn2HXuG315+Zo18ZI="
  project: "react-ohjelmointiprojekti"
